<a href="https://colab.research.google.com/github/Bavani86/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello Numpy")

Hello Numpy


In [ ]:
72+5*8

42

Array types and conversions between types

In [ ]:
import numpy as np
integers=np.array([1,34,2,3,9])
print(integers)

[ 1 34  2  3  9]


In [ ]:
integers[1]=4
print(integers)

[1 4 2 3 9]


In [ ]:
integers[1]

34

Replacing 34 as 4

Now we are going to change the value 1(int) as 14.5(float)which cannot be possible

In [ ]:
integers[0]=14.5
integers

array([14,  4,  2,  3,  9])

In the above one the value is truncated bcoz the numpy should contain only the same data type

In [ ]:
integers.dtype

dtype('int64')

In [ ]:
floats=np.array([1.2,3.4,5.6,7.8])
floats

array([1.2, 3.4, 5.6, 7.8])

In [ ]:
floats.dtype

dtype('float64')

Multidimensional arrays

In [ ]:
import numpy as np

In [ ]:
#One dimensional array
onedim_arr=np.array([1,2,3,4,5])
onedim_arr

array([1, 2, 3, 4, 5])

In [ ]:
#Two dimensional arrays
nums=np.array([[1,2,3,4,5],[6,7,8,9,10]])
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
nums[0,0]

1

In [ ]:
nums[1,4]

10

In [ ]:
nums[0,3]

4

In [ ]:
nums.ndim

2

In [ ]:
#Three dimensional array
multi_arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
multi_arr[0,1,2]

6

In [ ]:
multi_arr[1,1,1]

11

In [ ]:
multi_arr[1,0,1]

8

In [ ]:
fourdim_arr=np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[23,76],[45,54]]]])
fourdim_arr

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[23, 76],
         [45, 54]]]])

In [ ]:
#Creating arrays from lists and other python structures
import numpy as np
first_list=[1,2,3,4,5,6,7,8,9,10]
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
first_array=np.array(first_list)
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
second_list=[1,2,3,4.12,87000.67,5.98]

It contains both int & float

In [ ]:
second_array=np.array(second_list)
second_array

array([1.000000e+00, 2.000000e+00, 3.000000e+00, 4.120000e+00,
       8.700067e+04, 5.980000e+00])

In [ ]:
second_array.dtype

dtype('float64')

In [ ]:
Third_list=["bav",123,"nisha",455,"abi",678,"sista",970,"snow"]

In [ ]:
Third_array=np.array(Third_list)
Third_array

array(['bav', '123', 'nisha', '455', 'abi', '678', 'sista', '970', 'snow'],
      dtype='<U21')

When we create ndarray all the integers become string

In [ ]:
#Arrays from tuples(tuples are mutable and enclosed within the paranthesis)
first_tuple=(5,10,15,20,25)

In [ ]:
first_array=np.array(first_tuple)

In [ ]:
first_array

array([ 5, 10, 15, 20, 25])

In [ ]:
first_array.dtype

dtype('int64')

In [ ]:
multi_dim_list=[[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]]

In [ ]:
array_from_multi_dim_list=np.array(multi_dim_list)


In [ ]:
array_from_multi_dim_list

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

 NumPy array functions

In [ ]:
import numpy as np

1)numpy.arange(start,stop,step)

In [ ]:
integers_array=np.arange(10)
integers_array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#with start value and stop value
integers_second_array=np.arange(100,130)
integers_second_array


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [ ]:
#with start,stop,step
integers_third_array=np.arange(100,151,2)
integers_third_array


array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

2)numpy.linspace(start,stop,num(optional))

In [ ]:
first_floats_array=np.linspace(10,20)
first_floats_array

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [ ]:
Second_floats_array=np.linspace(10,20,5)
Second_floats_array

array([10. , 12.5, 15. , 17.5, 20. ])

3)numpy.random.rand

In [ ]:
#creating one dimensional array
first_rand_arr=np.random.rand(10)
first_rand_arr

array([0.14921519, 0.61346669, 0.50757742, 0.32641695, 0.96974603,
       0.88348152, 0.02103122, 0.75226604, 0.52183336, 0.74872907])

In [ ]:
#creating two dimensional array
Second_rand_arr=np.random.rand(4,4)
Second_rand_arr

array([[0.67519027, 0.24674481, 0.36586774, 0.88803673],
       [0.9494912 , 0.9308441 , 0.14047832, 0.82009345],
       [0.00916052, 0.41723586, 0.30909476, 0.46811865],
       [0.62879948, 0.32487608, 0.51223466, 0.03922536]])

4)numpy.random.randint(low,high,size)


In [ ]:
third_rand_arr=np.random.randint(0,100,20)
third_rand_arr

array([ 2, 47, 55,  5, 64, 67, 99, 25, 75, 23, 86,  4, 29, 31, 94, 72, 47,
       68, 22, 98])

Creating arrays filled with constant values

5)numpy.zeros

In [ ]:
import numpy as np

In [ ]:
first_z_array=np.zeros(5)
first_z_array


array([0., 0., 0., 0., 0.])

In [ ]:
second_z_array=np.zeros((4,5))
second_z_array


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

6)numpy.ones

In [ ]:
import numpy as np
first_ones_array=np.ones(5)
first_ones_array

array([1., 1., 1., 1., 1.])

In [ ]:
second_ones_array=np.ones((4,4))
second_ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
Third_ones_array=np.ones((4,5),dtype=int)
Third_ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

7)numpy.fill

In [ ]:
import numpy as np
first_fill_array=np.empty(10,dtype=int)
first_fill_array.fill(12)
first_fill_array


array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

8)numpy.full

In [ ]:
first_full_array=np.full(5,10)
first_full_array


array([10, 10, 10, 10, 10])

In [ ]:
second_full_array=np.full((4,5),8)
second_full_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

9)numpy.shape

In [ ]:
import numpy as np

In [ ]:
first_arr=np.arange(20)
first_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#Two dimensional array
second_arr=np.linspace((1,2),(10,20),10)
second_arr

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [ ]:
#Three dimensional array
third_arr=np.full((2,2,2),4)
third_arr

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [ ]:
#shape
np.shape(first_arr)

(20,)

In [ ]:
np.shape(second_arr)

(10, 2)

In [ ]:
np.shape(third_arr)

(2, 2, 2)

10)numpy.size(Total no of elements present in the array)

In [ ]:
np.size(first_arr)

20

In [ ]:
np.size(second_arr)

20

In [ ]:
np.size(third_arr)

8

Manipulate Numpy arrays

Adding elements

In [ ]:
import numpy as np
first_array=np.array([1,2,3,5])
first_array

array([1, 2, 3, 5])

In [ ]:
#using insert function(specify the index)
new_array=np.insert(first_array,3,4)
new_array

array([1, 2, 3, 4, 5])

In [ ]:
#using append function(appended to the end of the array)
new_array2=np.append(new_array,6)
new_array2

array([1, 2, 3, 4, 5, 6])

Removing elements

In [ ]:
#created an array
Third_arr=np.array([1,2,3,4,5])
Third_arr


array([1, 2, 3, 4, 5])

In [ ]:
#Deleting an element by the index
del_arr=np.delete(Third_arr,4)
del_arr


array([1, 2, 3, 4])

sorting elements

In [ ]:
integers_arr=np.random.randint(0,20,20)
integers_arr

array([ 8,  5,  1, 18,  8,  3,  5, 17, 13,  2,  8, 10,  4,  4,  2,  8, 10,
       13,  6,  3])

In [ ]:
print(np.sort(integers_arr))

[ 1  2  2  3  3  4  4  5  5  6  8  8  8  8 10 10 13 13 17 18]


In [ ]:
integers_2dim_arr=np.array([[3,8,5],[5,4,7]])
integers_2dim_arr

array([[3, 8, 5],
       [5, 4, 7]])

In [ ]:
print(np.sort(integers_2dim_arr))

[[3 5 8]
 [4 5 7]]


In [ ]:
colors=np.array(['white','blue','pink'])
colors

array(['white', 'blue', 'pink'], dtype='<U5')

In [ ]:
print(np.sort(colors))

['blue' 'pink' 'white']


copies and views

In [ ]:
import numpy as np

In [ ]:
students_ids_numbers=np.array([1111,1212,1313,1414,1515])
students_ids_numbers

array([1111, 1212, 1313, 1414, 1515])

In [ ]:
students_ids_numbers_reg=students_ids_numbers
print("id of students_ids_numbers",id(students_ids_numbers))
print("id of students_ids_numbers_reg",id(students_ids_numbers_reg))

id of students_ids_numbers 133150889469456
id of students_ids_numbers_reg 133150889469456


In [ ]:
students_ids_numbers_reg[1]=2222
print(students_ids_numbers)
print(students_ids_numbers_reg)

[1111 2222 1313 1414 1515]
[1111 2222 1313 1414 1515]


In [ ]:
students_ids_numbers_cp=students_ids_numbers.copy()
print(students_ids_numbers)

[1111 2222 1313 1414 1515]


In [ ]:
#value equality by using double equal operator
print(students_ids_numbers_cp==students_ids_numbers)



[ True  True  True  True  True]


In [ ]:
print("id of students_ids_number",id(students_ids_numbers))
print("id of students_ids_number_cp",id(students_ids_numbers_cp))

id of students_ids_number 133151745707824
id of students_ids_number_cp 133151311980912


In [ ]:
students_ids_numbers[0]=1000
print("original:",students_ids_numbers)
print("copy:",students_ids_numbers_cp)

original: [1000 2222 1313 1414 1515]
copy: [1111 2222 1313 1414 1515]


In [ ]:
students_ids_numbers_v=students_ids_numbers.view()

In [ ]:
#view
students_ids_numbers_v[0]=2000
print("original:",students_ids_numbers)
print("view:",students_ids_numbers_v)


original: [2000 2222 1313 1414 1515]
view: [2000 2222 1313 1414 1515]


Base

In [ ]:
print(students_ids_numbers_cp.base)
print(students_ids_numbers_v.base)

None
[2000 2222 1313 1414 1515]


Reshaping arrays

In [ ]:
import numpy as np

In [ ]:
first_arr=np.arange(1,13)
first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
second_arr=np.reshape(first_arr,(3,4))
second_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
Third_arr=np.reshape(first_arr,(6,2))
print(Third_arr)
print("Dimensions of Third_arr is",Third_arr.ndim)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Dimensions of Third_arr is 2


In [ ]:
fifth_arr=np.reshape(first_arr,(3,2,2))
print(fifth_arr)
print("Dimensions of fifth_arr is",fifth_arr.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Dimensions of fifth_arr is 3


In [ ]:
#Two dimensional array
sixth_arr=np.array([[1,2],[3,4],[5,6]])
sixth_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#flattening(converting n-dimensional array to one-dimensional array)
seventh_arr_flat=np.reshape(sixth_arr,-1)
seventh_arr_flat

array([1, 2, 3, 4, 5, 6])

In [ ]:
#flatten function and ravel function
eighth_arr_flat=sixth_arr.flatten()
print("eighth_arr_flat:",eighth_arr_flat)
ninth_arr_rav=sixth_arr.ravel()
print("ninth_arr_rav:",ninth_arr_rav)

eighth_arr_flat: [1 2 3 4 5 6]
ninth_arr_rav: [1 2 3 4 5 6]


In [ ]:
eighth_arr_flat[0]=100
eighth_arr_flat

array([100,   2,   3,   4,   5,   6])

In [ ]:
ninth_arr_rav[0]=200
ninth_arr_rav

array([200,   2,   3,   4,   5,   6])

Indexing and slicing

In [ ]:
import numpy as np

In [ ]:
twodim_arr=np.reshape(np.arange(12),(3,4))
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#accessing element from 1st row and second element
twodim_arr[1,1]

5

In [ ]:
twodim_arr[2,3]

11

In [ ]:
#accessing the whole row
twodim_arr[1]

array([4, 5, 6, 7])

In [ ]:
threedim_arr=np.reshape(np.arange(3*4*5),(3,4,5))
threedim_arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [ ]:
threedim_arr[0,2,3]

13

In [ ]:
threedim_arr[2,2,2]

52

In [ ]:
#accessing the last element from the array
threedim_arr[2,-1,-1]

59

In [ ]:
threedim_arr[1,-1,-1]

39

In [ ]:
import numpy as np
onedim_arr=np.arange(10)
onedim_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
onedim_arr[2:6]

array([2, 3, 4, 5])

In [ ]:
onedim_arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
onedim_arr[-3:]

array([7, 8, 9])

In [ ]:
#step
onedim_arr[::2]

array([0, 2, 4, 6, 8])

In [ ]:
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
twodim_arr[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [ ]:
twodim_arr[2:,2:]

array([[10, 11]])

In [ ]:
twodim_arr[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
twodim_arr[:,2]

array([ 2,  6, 10])

In [ ]:
twodim_arr[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
twodim_arr[1:2,2:]

array([[6, 7]])

In [ ]:
twodim_arr[0:3,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

Joining arrays

In [ ]:
#concatenate function
import numpy as np
first_arr=np.arange(1,11)
second_arr=np.arange(11,21)
print("first_arr",first_arr)
print("second_arr",second_arr)


first_arr [ 1  2  3  4  5  6  7  8  9 10]
second_arr [11 12 13 14 15 16 17 18 19 20]


In [ ]:
con_arr=np.concatenate((first_arr,second_arr))
con_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
third_2darr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
third_2darr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
fourth_2darr=np.array([[11,12,13,14,15],[16,17,18,19,20]])
fourth_2darr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
con2d_arr=np.concatenate((third_2darr,fourth_2darr))
con2d_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
#stack function
st_arr=np.stack((first_arr,second_arr))
st_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
#hstack function(horizontal)
hst_arr=np.hstack((first_arr,second_arr))
hst_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#vstack function(vertical)
vst_arr=np.vstack((first_arr,second_arr))
vst_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

Splitting arrays

In [ ]:
#split function
fifth_arr=np.arange(1,13)
fifth_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
sp_arr=np.array_split(fifth_arr,4)
sp_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [ ]:
print(sp_arr[1])

[4 5 6]


In [ ]:
sp_arr=np.array_split(fifth_arr,8)
sp_arr

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

In [ ]:
#hsplit function
hs_arr=np.hsplit(third_2darr,5)
hs_arr

[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

In [ ]:
#vsplit function
vs_arr=np.vsplit(third_2darr,2)
vs_arr

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]

Arithmetic operations

In [ ]:
import numpy as np
a=np.arange(1,11)
b=np.arange(21,31)
print("a",a)
print("b",b)

a [ 1  2  3  4  5  6  7  8  9 10]
b [21 22 23 24 25 26 27 28 29 30]


In [ ]:
#addition
a+b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [ ]:
#subtraction
b-a

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [ ]:
#Multiplication
a*b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [ ]:
#Division
a/b

array([0.04761905, 0.09090909, 0.13043478, 0.16666667, 0.2       ,
       0.23076923, 0.25925926, 0.28571429, 0.31034483, 0.33333333])

In [ ]:
#Exponentiation
a**b

array([                  1,             4194304,         94143178827,
           281474976710656,  298023223876953125, 4561031516192243712,
       5059972980857283351,                   0, 5756027422282277481,
       5076944270305263616])

In [ ]:
c=np.arange(2,12)
print("c",c)

c [ 2  3  4  5  6  7  8  9 10 11]


In [ ]:
a**c

array([           1,            8,           81,         1024,
              15625,       279936,      5764801,    134217728,
         3486784401, 100000000000])

In [ ]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Arithmetic functions

In [ ]:
np.add(a,b)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [ ]:
np.subtract(b,a)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [ ]:
np.multiply(a,b)

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [ ]:
np.divide(b,a)

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [ ]:
np.mod(b,a)

array([0, 0, 2, 0, 0, 2, 6, 4, 2, 0])

In [ ]:
np.power(a,c)

array([           1,            8,           81,         1024,
              15625,       279936,      5764801,    134217728,
         3486784401, 100000000000])

In [ ]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

Broadcasting

In [ ]:
import numpy as np
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b=np.arange(1,4)
b

array([1, 2, 3])

In [ ]:
#numpy effectively expanded the smaller array b
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [ ]:
c=np.arange(1,3)
c

array([1, 2])

In [ ]:
#3dim array
d=np.arange(24).reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
e=np.arange(4)
e

array([0, 1, 2, 3])

In [ ]:
d-e

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

Aggregate functions

In [2]:
import numpy as np

In [5]:
#onedim array
first_arr=np.arange(10,110,10)
first_arr


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [16]:
#Two dim array
second_arr=np.arange(10,100,10).reshape(3,3)
second_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [7]:
Third_arr=np.arange(10,110,10).reshape(2,5)
Third_arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [10]:
#sum()
first_arr.sum()

550

In [15]:
second_arr.sum()

450

In [12]:
Third_arr.sum()

550

In [18]:
#calculate the sum of each column in the second array
second_arr.sum(axis=0)

array([120, 150, 180])

In [19]:
#calculate the sum of each row in the second array
second_arr.sum(axis=1)

array([ 60, 150, 240])

In [20]:
#prod()
first_arr.prod()

36288000000000000

In [21]:
second_arr.prod()

362880000000000

In [22]:
Third_arr.prod()

36288000000000000

In [24]:
#calculating the product of each column in the third array
Third_arr.prod(axis=0)

array([ 600, 1400, 2400, 3600, 5000])

In [25]:
#calculating the product of each row in the third array
Third_arr.prod(axis=1)

array([  12000000, 3024000000])

In [26]:
#average()
np.average(first_arr)

55.0

In [27]:
np.average(second_arr)

50.0

In [28]:
np.average(Third_arr)

55.0

In [29]:
#min()
np.min(first_arr)

10

In [30]:
#max()
np.max(first_arr)

100

In [31]:
#mean
np.mean(first_arr)

55.0

In [32]:
#standard deviation
np.std(first_arr)

28.722813232690143

How to get unique items and counts

In [33]:
#We are creating an one dim array with some duplicate values
import numpy as np
first_arr=np.array([1,2,3,4,5,6,1,2,7,2,1,10,7,8])

In [34]:
np.unique(first_arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [45]:
#Two dim array with duplicate values
second_arr=np.array([[1,1,2,1],[3,1,2,1],[1,1,2,1],[7,1,1,1]])
second_arr

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [1, 1, 2, 1],
       [7, 1, 1, 1]])

In [46]:
np.unique(second_arr)

array([1, 2, 3, 7])

In [49]:
#printed without duplicate rows
np.unique(second_arr,axis=0)


array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [7, 1, 1, 1]])

In [48]:
#printed without duplicate columns
np.unique(second_arr,axis=1)

array([[1, 1, 2],
       [1, 3, 2],
       [1, 1, 2],
       [1, 7, 1]])

In [50]:
#To get index position of unique values
np.unique(first_arr,return_index=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 10]),
 array([ 0,  1,  2,  3,  4,  5,  8, 13, 11]))

In [53]:
#To get frequency count of unique elements
np.unique(second_arr,return_counts=True)

(array([1, 2, 3, 7]), array([11,  3,  1,  1]))

Transpose like operations(converting rows as columns and columns as rows)

In [54]:
import numpy as np
first2dim_arr=np.arange(12).reshape((3,4))
first2dim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
np.transpose(first2dim_arr)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [56]:
second2dim_arr=np.arange(6).reshape(3,2)
second2dim_arr

array([[0, 1],
       [2, 3],
       [4, 5]])

numpy.moveaxis()

In [60]:
first3dim_arr=np.arange(24).reshape(2,3,4)
first3dim_arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [61]:
np.moveaxis(first3dim_arr,0,-1)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

numpy.swapaxes()

In [64]:
np.swapaxes(first3dim_arr,0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

Reversing an array

In [65]:
import numpy as np
arr_1dim=[10,1,9,2,8,3,7,4,6,5]
arr_1dim

[10, 1, 9, 2, 8, 3, 7, 4, 6, 5]

In [66]:
arr_1dim[::-1]

[5, 6, 4, 7, 3, 8, 2, 9, 1, 10]

flip function()

In [67]:
np.flip(arr_1dim)

array([ 5,  6,  4,  7,  3,  8,  2,  9,  1, 10])

In [68]:
arr_2dim=np.arange(9).reshape(3,3)
arr_2dim

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
np.flip(arr_2dim)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [72]:
#column reversing
np.flip(arr_2dim,0)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [73]:
#row reversing
np.flip(arr_2dim,1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [74]:
arr_3dim=np.arange(24).reshape(2,3,4)
arr_3dim

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [75]:
#3dim reversing
np.flip(arr_3dim)

array([[[23, 22, 21, 20],
        [19, 18, 17, 16],
        [15, 14, 13, 12]],

       [[11, 10,  9,  8],
        [ 7,  6,  5,  4],
        [ 3,  2,  1,  0]]])

In [76]:
#3dim row reversing
np.flip(arr_3dim,1)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [77]:
#3dim col reversing
np.flip(arr_3dim,0)

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])